### PR TITLE
Typing support

### PR DESCRIPTION
**Pull request by StefRave**
The typings are now generated from the source files and will be distributed in a dist directory.
This means that projects that use webcola through npm will automatically will use uptodate typings.
Do do this I had to make some minor fixes to the original code and remove local references.

### CODE REVIEW

**Comment by StefRave** [comment]
It seems I got the same idea as @AltekkeE in #222 
I am using d3 v4 in my own project, so this pull request should also fix #220

**Comment by tgdwyer** [comment]
Thank you!

**Comment by jrbotros** [comment]
@tgdwyer can you publish this to npm as v3.3.4 when you get a chance? Thanks so much!

**Comment by tgdwyer** [comment]
Done!  Thank you.

**Pull request merged**
