### PR TITLE
Fix: Add compiled JS files

### PR DESCRIPTION
**Pull request by gcallaghan**
Not all consumers are Typescript projects. This changeset adds the
compiled JS files for direct consumption from NPM.

### CODE REVIEW

**Comment by tgdwyer** [comment]
fair enough!

**Comment by chris-dickson** [comment]
Has this version been published to npm yet?  Looks like the latest available is 3.3.0, but you made this fix after that update.

**Comment by gcallaghan** [comment]
I just pointed my package.json at `"webcola": "tgdwyer/WebCola#master" ` for the moment.

**Comment by tgdwyer** [comment]
I have updated tag v3.3.0 to the commit that includes the generated js.

**Pull request merged**
