### PR TITLE
update version in bower.json

### PR DESCRIPTION
**Pull request by qinfchen**

### CODE REVIEW

**Comment by qinfchen** [comment]
@tgdwyer I noticed that the latest release on npm is 3.1.3. Can we create a 3.1.3 tag after this gets merged?

Thanks

**Comment by tgdwyer** [comment]
tagged v3.1.3

**Comment by qinfchen** [comment]
awesome, thank you!

**Comment by maxkfranz** [comment]
@tgdwyer It's actually not necessary for bower.json to have the `version` field anymore.  It just uses the tags in the git repo, so it suffices to tag each release before publishing to npm -- and bower will be updated automatically.

The `cytoscape-cola` extension supports bower and npm, but putting `webcola` as a dependency in `bower.json` caused issues as there weren't those corresponding tags for bower.

Thanks for your work on Cola.  It's a great layout!

**Pull request merged**
