### PR TITLE
Allow restarting without re-centering graph

### LINKED ISSUE #244: specify starting position of nodes
Hi, I'm trying to do something very similar to aspiers in this issue - #63 , but instead of dagre we have precalculated node positions. However initializing the x & y of the nodes does not seem to work and they just spawn in the center. Here is a [jsbin](https://jsbin.com/rejitej/5/edit?js,console,output) showing the issue. It simply tries to place two nodes in the upper left corner instead of in the center. This approach works with the original D3 force. Also if I don't start cola the nodes are rendered in the upper left corner. I think I'm setting up things properly so this should work.

### PR DESCRIPTION
**Pull request by worldsayshi**
This should fix #244. It adds another optional parameter to `simulation.start()` though. Perhaps we should consider adding an options object as parameter instead of additional parameters?

### CODE REVIEW

**Comment by worldsayshi** [comment]
Notice that I upped the version number since this introduces a new feature.

**Comment by worldsayshi** [comment]
To clarify the commits a bit: I first did a false solution that I reverted in the later commits.

**Comment by worldsayshi** [comment]
Oh, I realize that the version change wasn't semver correct. Will fix.

**Comment by tgdwyer** [comment]
Thank you!

**Comment by Hugo-Trentesaux** [comment]
I do not understand: calling start on cola d3 adaptor with centerGraph=false *do* center the graph.

**Comment by Hugo-Trentesaux** [comment]
I do not understand how it is supposed to work: I downloaded the last version of the code (with the commit 2b6a7564), compiled it, used the minified cola file, called start with `centerGraph=false`, but it keeps centering the graph. What did I did wrong?

**Comment by worldsayshi** [comment]
@Hugo-Trentesaux See if my [comments on the related issue](https://github.com/tgdwyer/WebCola/issues/244#issuecomment-406869957) brings any clarity and try debugging. Hard to be of any more help without code example.

**Pull request merged**
